const theaterTypes = {
  FETCH_HE_THONG_RAP_START: "FETCH_HE_THONG_RAP_START",
  FETCH_HE_THONG_RAP_SUCCESS: "FETCH_HE_THONG_RAP_SUCCESS",
  FETCH_HE_THONG_RAP_ERROR: "FETCH_HE_THONG_RAP_ERROR",

  FETCH_THONG_TIN_CUM_RAP_SUCCESS: "FETCH_THONG_TIN_CUM_RAP_SUCCESS",
  FETCH_THONG_TIN_LICH_CHIEU_SUCCESS: "FETCH_THONG_TIN_LICH_CHIEU_SUCCESS",

  UPDATE_CUM_RAP_THEO_HE_THONG_RAP_SUCCESS:
    "UPDATE_CUM_RAP_THEO_HE_THONG_RAP_SUCCESS",
  UPDATE_LICH_CHIEU_THEO_HE_THONG_RAP_SUCCESS:
    "UPDATE_LICH_CHIEU_THEO_HE_THONG_RAP_SUCCESS",
};
export default theaterTypes;
