const movieTypes = {
  FETCH_MOVIES_START: "FETCH_MOVIES_START",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_ERROR: "FETCH_MOVIES_ERROR",
  FETCH_MOVIE_DETAILS_REQUEST: "FETCH_MOVIE_DETAILS_REQUEST",
  FETCH_MOVIE_DETAILS: "FETCH_MOVIE_DETAILS",
  FETCH_MOVIE_DETAILS_ERROR: "FETCH_MOVIE_DETAILS_ERROR",
  FETCH_MOVIE_TICKET_REQUEST: "FETCH_MOVIE_DETAILS_REQUEST",
  FETCH_MOVIE_TICKET_SUCCESS: "FETCH_MOVIE_DETAILS_SUCCESS",
  FETCH_MOVIE_TICKET_ERROR: "FETCH_MOVIE_DETAILS_ERROR",
  SEARCH_MOVIE_SUCCESS: "SEARCH_MOVIE_SUCCESS",
};
export default movieTypes;
