const userTypes = {
  //User login
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  // User  signup
  USER_SIGNUP_REQUEST: "USER_SIGNUP_REQUEST",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAILED: "USER_SIGNUP_FAILED",
  //User logout
  USER_LOGOUT: "USER_LOGOUT",
  //User clear data
  USER_CLEAR_DATA: "USER_CLEAR_DATA",
  //User info
  USER_INFO_REQUEST: "USER_INFO_REQUEST",
  USER_INFO_SUCCESS: "USER_INFO_SUCCESS",
  USER_INFO_ERROR: "USER_INFO_ERROR",
  //Update User;
  UPDATE_USER_INFO_SUCCESS: "UPDATE_USER_INFO_SUCCESS",
  //Fetch all user
  FETCH_USERS_START: "FETCH_USERS_START",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_ERROR: "FETCH_USERS_ERROR",
  //Search User
  SEARCH_USER_SUCCESS: "SEARCH_USER_SUCCESS",
  //ADD USER:
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
};
export default userTypes;
